export const responseCodes = {
  '00': 'Approved / Success',
  '01': 'Pending — poll requery',
  '05': 'Do not honor',
  '06': 'General error',
  '12': 'Invalid transaction',
  '14': 'Invalid card number',
  '25': 'Unable to locate record',
  '51': 'Insufficient funds',
  '54': 'Expired card',
  '57': 'Transaction not permitted to cardholder',
  '62': 'Restricted card',
  '65': 'Exceeds withdrawal limit',
  '68': 'Response received too late',
  '91': 'Issuer or switch inoperative',
  '96': 'System malfunction',
  '90000': 'VAS / Quickteller success',
  '10400': 'Bad request / validation error',
  '10403': 'Unauthorized / operation not permitted',
  '10404': 'Not found',
  '10409': 'Duplicate / entity already exists',
  '10500': 'Server error — retry',
  S00: 'Salary lending success',
  S201: 'Salary repayment notification successful',
};
