/**
 * Interswitch MCP tool group implemented from INTERSWITCH_MCP_SKILL.md.
 * Sandbox behavior depends on configured Interswitch credentials and documented endpoint availability.
 */
import { z } from 'zod';
import type { RegisteredTool } from '../types/tool.js';
import { lendingClient } from '../clients/lending-client.js';
import { resolveKoboAmount } from '../utils/amount.js';
import { requireWriteConfirmation } from '../utils/confirmation.js';
import { normalizeResponse } from '../utils/normalizer.js';
import { jsonContent, normalizedContent } from '../utils/mcp.js';
import { toInterswitchError } from '../utils/errors.js';
import { amountProperties, confirmProperty } from './schemas.js';

async function invoke<T>(fn: () => Promise<T>) { try { return normalizedContent(normalizeResponse(await fn())); } catch (error) { const e = toInterswitchError(error); return jsonContent({ success: false, responseCode: e.responseCode, message: e.responseDescription, data: null, raw: e.raw }, true); } }
const LoanSchema = z.object({ customerId: z.string(), amountNaira: z.number().positive().optional(), amountKobo: z.number().int().positive().optional(), tenor: z.number().optional(), merchantCode: z.string().optional(), transactionRef: z.string().optional(), employerCode: z.string().optional(), productCode: z.string().optional(), confirm: z.boolean().optional(), extra: z.record(z.unknown()).optional() });
const CustomerSchema = z.object({ customerId: z.string(), fromDate: z.string().optional(), toDate: z.string().optional(), extra: z.record(z.unknown()).optional() });
function loanBody(p: z.infer<typeof LoanSchema>) { return { customerId: p.customerId, amount: p.amountNaira || p.amountKobo ? resolveKoboAmount(p) : undefined, tenor: p.tenor, merchantCode: p.merchantCode, transactionRef: p.transactionRef, employerCode: p.employerCode, productCode: p.productCode, ...p.extra }; }

export const tools: RegisteredTool[] = [
  { definition: { name: 'isw_request_nano_loan', description: 'Request a nano loan. High-risk operation creating debt; requires confirm: true.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, ...amountProperties, tenor: { type: 'number' }, merchantCode: { type: 'string' }, transactionRef: { type: 'string' }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = LoanSchema.parse(args); requireWriteConfirmation('isw_request_nano_loan', p, 'write', 'high'); return invoke(() => lendingClient.post('/api/v2/lending/nanoloans', loanBody(p))); } },
  { definition: { name: 'isw_salary_lending', description: 'Request a salary loan. High-risk operation creating debt; requires confirm: true.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, ...amountProperties, tenor: { type: 'number' }, employerCode: { type: 'string' }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = LoanSchema.parse(args); requireWriteConfirmation('isw_salary_lending', p, 'write', 'high'); return invoke(() => lendingClient.post('/api/v2/lending/salaryloans', loanBody(p))); } },
  { definition: { name: 'isw_value_financing', description: 'Request value financing. High-risk operation creating debt; requires confirm: true.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, ...amountProperties, productCode: { type: 'string' }, merchantCode: { type: 'string' }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = LoanSchema.parse(args); requireWriteConfirmation('isw_value_financing', p, 'write', 'high'); return invoke(() => lendingClient.post('/api/v2/lending/valuefinancing', loanBody(p))); } },
  { definition: { name: 'isw_get_customer_demographics', description: 'Get customer demographic profile.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'read', risk: 'low', handler: async (args) => { const p = CustomerSchema.parse(args); return invoke(() => lendingClient.get(`/api/v2/insights/customers/${encodeURIComponent(p.customerId)}/demographics`, { query: p.extra })); } },
  { definition: { name: 'isw_get_financial_history', description: 'Get customer financial history.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, fromDate: { type: 'string' }, toDate: { type: 'string' }, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'read', risk: 'low', handler: async (args) => { const p = CustomerSchema.parse(args); return invoke(() => lendingClient.get(`/api/v2/insights/customers/${encodeURIComponent(p.customerId)}/financial-history`, { query: { fromDate: p.fromDate, toDate: p.toDate, ...p.extra } })); } },
  { definition: { name: 'isw_get_financial_history_average', description: 'Get customer average financial history.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'read', risk: 'low', handler: async (args) => { const p = CustomerSchema.parse(args); return invoke(() => lendingClient.get(`/api/v2/insights/customers/${encodeURIComponent(p.customerId)}/financial-history/average`, { query: p.extra })); } },
  { definition: { name: 'isw_get_financial_habits', description: 'Get customer financial habits.', inputSchema: { type: 'object', properties: { customerId: { type: 'string' }, extra: { type: 'object' } }, required: ['customerId'] } }, mode: 'read', risk: 'low', handler: async (args) => { const p = CustomerSchema.parse(args); return invoke(() => lendingClient.get(`/api/v2/insights/customers/${encodeURIComponent(p.customerId)}/financial-habits`, { query: p.extra })); } },
];
