/**
 * Interswitch MCP tool group implemented from INTERSWITCH_MCP_SKILL.md.
 * Sandbox behavior depends on configured Interswitch credentials and documented endpoint availability.
 */
import { z } from 'zod';
import type { RegisteredTool } from '../types/tool.js';
import { config, requireConfigValue } from '../config/config.js';
import { transfersClient } from '../clients/transfers-client.js';
import { resolveKoboAmount } from '../utils/amount.js';
import { requireWriteConfirmation } from '../utils/confirmation.js';
import { normalizeResponse } from '../utils/normalizer.js';
import { jsonContent, normalizedContent } from '../utils/mcp.js';
import { toInterswitchError } from '../utils/errors.js';
import { amountProperties, confirmProperty } from './schemas.js';

async function invoke<T>(fn: () => Promise<T>) { try { return normalizedContent(normalizeResponse(await fn())); } catch (error) { const e = toInterswitchError(error); return jsonContent({ success: false, responseCode: e.responseCode, message: e.responseDescription, data: null, raw: e.raw }, true); } }

const SingleTransferSchema = z.object({ amountNaira: z.number().positive().optional(), amountKobo: z.number().int().positive().optional(), initiatingEntityCode: z.string().optional(), beneficiaryAccountName: z.string(), beneficiaryAccountNumber: z.string(), beneficiaryBankCode: z.string(), senderName: z.string(), narration: z.string().optional(), transactionRef: z.string(), confirm: z.boolean().optional(), extra: z.record(z.unknown()).optional() });
const ResolveBankSchema = z.object({ beneficiaryAccountNumber: z.string(), beneficiaryBankCode: z.string() });
const BulkTransferSchema = z.object({ initiatingEntityCode: z.string().optional(), narration: z.string().optional(), transactions: z.array(SingleTransferSchema.omit({ confirm: true })).max(100), confirm: z.boolean().optional(), extra: z.record(z.unknown()).optional() });

export const tools: RegisteredTool[] = [
  { definition: { name: 'isw_single_transfer', description: 'Send money to a bank account. High-risk financial operation; requires confirm: true. Provide amountNaira or amountKobo explicitly.', inputSchema: { type: 'object', properties: { ...amountProperties, initiatingEntityCode: { type: 'string' }, beneficiaryAccountName: { type: 'string' }, beneficiaryAccountNumber: { type: 'string' }, beneficiaryBankCode: { type: 'string' }, senderName: { type: 'string' }, narration: { type: 'string' }, transactionRef: { type: 'string' }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['beneficiaryAccountName', 'beneficiaryAccountNumber', 'beneficiaryBankCode', 'senderName', 'transactionRef'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = SingleTransferSchema.parse(args); requireWriteConfirmation('isw_single_transfer', p, 'write', 'high'); return invoke(() => transfersClient.post('/api/v2/ft/transfer', { initiatingEntityCode: p.initiatingEntityCode ?? requireConfigValue(config.core.initiatingEntityCode, 'INTERSWITCH_INITIATING_ENTITY_CODE'), beneficiaryAccountName: p.beneficiaryAccountName, beneficiaryAccountNumber: p.beneficiaryAccountNumber, beneficiaryBankCode: p.beneficiaryBankCode, senderName: p.senderName, narration: p.narration, transactionRef: p.transactionRef, amount: resolveKoboAmount(p), ...p.extra })); } },
  { definition: { name: 'isw_bulk_transfer', description: 'Send money to multiple bank accounts. High-risk financial operation; requires confirm: true. Max 100 transactions.', inputSchema: { type: 'object', properties: { initiatingEntityCode: { type: 'string' }, narration: { type: 'string' }, transactions: { type: 'array', maxItems: 100, items: { type: 'object' } }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['transactions'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = BulkTransferSchema.parse(args); requireWriteConfirmation('isw_bulk_transfer', p, 'write', 'high'); return invoke(() => transfersClient.post('/api/v2/ft/transfer/bulk', { initiatingEntityCode: p.initiatingEntityCode ?? requireConfigValue(config.core.initiatingEntityCode, 'INTERSWITCH_INITIATING_ENTITY_CODE'), narration: p.narration, transactions: p.transactions.map((tx) => ({ initiatingEntityCode: tx.initiatingEntityCode, beneficiaryAccountName: tx.beneficiaryAccountName, beneficiaryAccountNumber: tx.beneficiaryAccountNumber, beneficiaryBankCode: tx.beneficiaryBankCode, senderName: tx.senderName, narration: tx.narration, transactionRef: tx.transactionRef, amount: resolveKoboAmount(tx), ...tx.extra })), ...p.extra })); } },
  { definition: { name: 'isw_resolve_bank_account', description: 'Resolve account name before transfer.', inputSchema: { type: 'object', properties: { beneficiaryAccountNumber: { type: 'string' }, beneficiaryBankCode: { type: 'string' } }, required: ['beneficiaryAccountNumber', 'beneficiaryBankCode'] } }, mode: 'read', risk: 'low', handler: async (args) => { const p = ResolveBankSchema.parse(args); return invoke(() => transfersClient.post('/api/v2/ft/enquiry/nameenquiry', p)); } },
  { definition: { name: 'isw_get_bank_codes', description: 'List supported bank codes for transfers.', inputSchema: { type: 'object', properties: {} } }, mode: 'read', risk: 'low', handler: async () => invoke(() => transfersClient.get('/api/v2/ft/beneficiaries/banks')) },
  { definition: { name: 'isw_agency_banking_cashout', description: 'Perform agency banking cashout. High-risk financial operation; requires confirm: true.', inputSchema: { type: 'object', properties: { ...amountProperties, agentCode: { type: 'string' }, transactionRef: { type: 'string' }, customerAccount: { type: 'string' }, customerBankCode: { type: 'string' }, confirm: confirmProperty, extra: { type: 'object' } }, required: ['agentCode', 'transactionRef', 'customerAccount', 'customerBankCode'] } }, mode: 'write', risk: 'high', handler: async (args) => { const p = z.object({ amountNaira: z.number().positive().optional(), amountKobo: z.number().int().positive().optional(), agentCode: z.string(), transactionRef: z.string(), customerAccount: z.string(), customerBankCode: z.string(), confirm: z.boolean().optional(), extra: z.record(z.unknown()).optional() }).parse(args); requireWriteConfirmation('isw_agency_banking_cashout', p, 'write', 'high'); return invoke(() => transfersClient.post('/api/v2/ft/transfer/agentcashout', { amount: resolveKoboAmount(p), agentCode: p.agentCode, transactionRef: p.transactionRef, customerAccount: p.customerAccount, customerBankCode: p.customerBankCode, ...p.extra })); } },
];
